apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: skaffold-create-react-app
build:
  artifacts:
    - image: skaffold-create-react-app
      sync:
        infer:
          - "**/*.js"
          - "**/*.jsx"
          - "**/*.css"
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: deployment
    resourceName: create-react-app
    port: 3000
